### ISSUE TITLE
SQL file

### ISSUE THREAD

**Issue by brangsmith** [apurva-modi/WSPT-quiz-webApp#1]
Hi - code looks great. Is there a SQL file for this?

**Comment by apurva-modi** [comment]
Yes, there is a SQL file but I intentionally didn't add it here because this project is currently in productions and the SQL file contains questions and related answers to it.

**Comment by brangsmith** [comment]
> Yes, there is a SQL file but I intentionally didn't add it here because this project is currently in productions and the SQL file contains questions and related answers to it.

Thanks for your quick response!

Is it possible if I can kindly ask for the database structure? Currently attempting to reverse engineer the tables based on code..

**Comment by apurva-modi** [comment]
Okay, I have added a SQL dump named "wspt.sql" to the repo for you to use and test this web application.
If you like it please leave a star.
